"""Add Stripe payment integration: User Stripe fields, StubListing payment fields, StubOrder and StubPayment models

Revision ID: 8a16549428be
Revises: 
Create Date: 2025-07-04 18:40:55.090001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a16549428be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stub_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_required', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reserved_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserved_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stub_listing_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_stub_listing_reserved_by_user', 'user', ['reserved_by_user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_account_status', sa.String(length=20), nullable=True, server_default='pending'))
        batch_op.add_column(sa.Column('stripe_onboarding_completed', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_capabilities_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stripe_requirements_due', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('seller_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seller_verification_level', sa.String(length=20), nullable=False, server_default='unverified'))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_seller'), ['is_seller'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_seller_verification_level'), ['seller_verification_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stripe_account_id'), ['stripe_account_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_stripe_account_status'), ['stripe_account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stripe_onboarding_completed'), ['stripe_onboarding_completed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stripe_onboarding_completed'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_account_status'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_account_id'))
        batch_op.drop_index(batch_op.f('ix_user_seller_verification_level'))
        batch_op.drop_index(batch_op.f('ix_user_is_seller'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('seller_verification_level')
        batch_op.drop_column('seller_bio')
        batch_op.drop_column('is_seller')
        batch_op.drop_column('stripe_requirements_due')
        batch_op.drop_column('stripe_capabilities_enabled')
        batch_op.drop_column('stripe_onboarding_completed')
        batch_op.drop_column('stripe_account_status')
        batch_op.drop_column('stripe_account_id')

    with op.batch_alter_table('stub_listing', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stub_listing_reserved_by_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stub_listing_status'))
        batch_op.drop_column('reserved_by_user_id')
        batch_op.drop_column('reserved_until')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('payment_required')

    # ### end Alembic commands ###
