"""Add currency column to stub

Revision ID: 99e9e3fa814a
Revises: 
Create Date: 2025-05-30 22:56:20.901487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e9e3fa814a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stub', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
